name: Java CI with maven

on:
	push: 
		branches: ["main"]
	pull_request:
		branches: ["main"]

jobs:
	validate:
		runs-on: ubuntu-latest
		steps:
		- name: Fetch Remote Repository Code
		  uses: actions/checkout@v4
		- name: Initialize OpenJDK 25 environment
		  uses: actions/setup-java@v4
		  with:
			java-version: "25.0.4+1"
			distribution: "temurin"
			cache: maven
		- name: Run complete test engine pipeline
		  run: mvn clean test
